In [2]:
import pandas as pd

In [47]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
file_dir = '/Users/justinobrien/Desktop/biking/'
biking = pd.read_csv(f'{file_dir}citibike.csv')

In [48]:
# 2. Check the datatypes of your columns. 
biking.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [49]:
# 3. Convert the 'tripduration' column to datetime datatype.
biking['tripduration'] = pd.to_datetime(biking['tripduration'], unit ='s')

In [50]:
# 4. Check the datatypes of your columns. 
biking.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2344219,1970-01-01 00:03:36,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,1
2344220,1970-01-01 00:01:57,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,2
2344221,1970-01-01 00:26:54,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,0
2344222,1970-01-01 00:21:41,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,0
2344223,1970-01-01 00:06:59,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,1

In [52]:
# 5. Export the Dataframe as a new CSV file without the index.
biking.to_csv(r'/Users/justinobrien/Desktop/biking/biking.csv', index = False)